export const FETCH_ACTIVITIES = 'FETCH_ACTIVITIES';
export const UPDATE_ACTIVITY = 'UPDATE_ACTIVITY';
export const INSERT_ACTIVITY = "INSERT_ACTIVITY";
export const DELETE_ACTIVITY = "DELETE_ACTIVITY";

export const FETCH_AREAS = 'FETCH_AREAS';